### PR TITLE
[trigger] Remove redundant check for self-authorship

### PR DESCRIPTION
**Pull request by calebj**
`bot.user_allowed(message)` already does this

### CODE REVIEW

**Comment by Twentysix26** [comment]
As I see in `user_allowed` this might cause issues to self bots (although they really should not use this cog). Closing, I doubt this simple check has any meaningful impact on performances anyway

**Comment by skeith** [comment]
Noooooo~

*screaming intensifies

**Comment by calebj** [comment]
I prevented selfbot-triggering with https://github.com/calebj/Red-DiscordBot/blob/selfbot/red_self.py#L173, and it's reliable. Only the user would be able to trigger their selfbot.

Would be neater if it had the option to edit or delete the original message in this case, too.

**Comment by skeith** [comment]
I wanted a toggle on trigger for selfbot. I sometimes want it to trigger on other user messages

**Comment by calebj** [comment]
> I sometimes want it to trigger on other user messages

Er, no. That's against Discord ToS for userbots, and I won't support it. Feel free to write it yourself, though.

**Comment by skeith** [comment]
Then I assume you wil be removing your status(away) cog from selfbot distribution since it was basically similar

**Comment by calebj** [comment]
What distribution again?

**Comment by skeith** [comment]
If i am not mistaken. Cloning the selfbot from your fork (branch selfbot) comes with a cog called status (for away status)

**Comment by calebj** [comment]
It does not, and never did. [Check for yourself](https://github.com/calebj/Red-DiscordBot/tree/selfbot/cogs).

**Comment by skeith** [comment]
God. I am mixing something up. My apologies

**Pull request closed without merging**
